
development:
  adapter: postgresql
  encoding: unicode
  database: project1_development
  pool: 5
  username: postgres
  password: admin


test:
  adapter: postgresql
  encoding: unicode
  database: project1_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: project1_production
  pool: 5
  username: postgres
  password: admin