# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 280ab8bd04986a435ae4476ab394830cc091cd99e75c9c3df3dc807323ce7f9c70ca32db45e0fe594697c50d7df9143185754f4e88c98a47645899d452522bd6

test:
  secret_key_base: b4b4fd0397677827107351c21c48fec19d0fb52c76d0a9750598d3dde5ed86b46b7da82eded078303e95112361013183260625f4093133f59dc8d83104a6a060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
